-- WSP-ISAP - Base inicial para Supabase Postgres
-- Ejecutar este script en el SQL Editor de Supabase.
-- Mantiene compatibilidad de nombres con el esquema actual en SQLite.

create extension if not exists pgcrypto;

do $$
begin
  if not exists (select 1 from pg_type where typname = 'isapre_id') then
    create type public.isapre_id as enum (
      'colmena',
      'banmedica',
      'consalud',
      'cruzblanca',
      'nueva_masvida',
      'vida_tres',
      'esencial'
    );
  end if;

  if not exists (select 1 from pg_type where typname = 'estado_solicitud') then
    create type public.estado_solicitud as enum (
      'en_cola',
      'procesando_ocr',
      'iniciando_sesion',
      'subiendo_boleta',
      'exitoso',
      'rechazado'
    );
  end if;

  if not exists (select 1 from pg_type where typname = 'portal_status') then
    create type public.portal_status as enum (
      'operativo',
      'caido',
      'html_cambiado',
      'mantenimiento'
    );
  end if;

  if not exists (select 1 from pg_type where typname = 'estado_proceso_demo') then
    create type public.estado_proceso_demo as enum (
      'pendiente',
      'en_progreso',
      'completado',
      'fallido'
    );
  end if;

  if not exists (select 1 from pg_type where typname = 'direccion_mensaje') then
    create type public.direccion_mensaje as enum (
      'entrante',
      'saliente',
      'sistema'
    );
  end if;

  if not exists (select 1 from pg_type where typname = 'tipo_mensaje_whatsapp') then
    create type public.tipo_mensaje_whatsapp as enum (
      'text',
      'image',
      'interactive',
      'document',
      'audio',
      'system'
    );
  end if;

  if not exists (select 1 from pg_type where typname = 'etapa_conversacion') then
    create type public.etapa_conversacion as enum (
      'idle',
      'awaiting_prestacion',
      'awaiting_field',
      'processing',
      'completed'
    );
  end if;
end $$;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create table if not exists public.usuarios (
  id integer generated by default as identity primary key,
  nombre text not null,
  telefono text not null unique,
  rut text not null,
  password_hash text not null,
  accepted_privacy_policy_at timestamptz,
  accepted_terms_at timestamptz,
  consent_ip text,
  consent_user_agent text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

alter table public.usuarios
  add column if not exists accepted_privacy_policy_at timestamptz,
  add column if not exists accepted_terms_at timestamptz,
  add column if not exists consent_ip text,
  add column if not exists consent_user_agent text;

create table if not exists public.credenciales_isapre (
  id integer generated by default as identity primary key,
  usuario_id integer not null references public.usuarios(id) on delete cascade,
  isapre_id public.isapre_id not null,
  rut text not null,
  password_encrypted text not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (usuario_id, isapre_id)
);

create table if not exists public.reembolsos (
  id integer generated by default as identity primary key,
  usuario_id integer not null references public.usuarios(id) on delete cascade,
  rut_usuario text not null,
  isapre public.isapre_id not null,
  monto integer not null default 0 check (monto >= 0),
  fecha timestamptz not null default timezone('utc', now()),
  estado public.estado_solicitud not null default 'en_cola',
  url_documento text not null,
  folio_isapre text,
  error text,
  intentos integer not null default 0 check (intentos >= 0),
  locked_at timestamptz,
  worker_id text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.portales_status (
  isapre_id public.isapre_id primary key,
  status public.portal_status not null default 'operativo',
  ultima_ejecucion_exitosa timestamptz not null default timezone('utc', now()),
  latencia_ms integer,
  mensaje_error text,
  updated_at timestamptz not null default timezone('utc', now()),
  constraint portales_status_latencia_ms_check
    check (latencia_ms is null or latencia_ms >= 0)
);

create table if not exists public.conversaciones_whatsapp (
  id integer generated by default as identity primary key,
  usuario_id integer references public.usuarios(id) on delete set null,
  telefono text not null,
  canal text not null default 'whatsapp',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (telefono, canal)
);

create table if not exists public.mensajes_whatsapp (
  id integer generated by default as identity primary key,
  conversacion_id integer not null references public.conversaciones_whatsapp(id) on delete cascade,
  direccion public.direccion_mensaje not null,
  tipo public.tipo_mensaje_whatsapp not null default 'text',
  contenido text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.webhook_events (
  id integer generated by default as identity primary key,
  idempotency_key text not null unique,
  event_name text not null,
  payload jsonb not null default '{}'::jsonb,
  processed_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.catalogo_prestaciones (
  id integer generated by default as identity primary key,
  isapre_id public.isapre_id not null,
  codigo text not null,
  nombre text not null,
  descripcion text,
  requiere_formulario boolean not null default false,
  requiere_adjuntos boolean not null default false,
  activa boolean not null default true,
  orden integer not null default 0,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (isapre_id, codigo)
);

create table if not exists public.catalogo_campos_prestacion (
  id integer generated by default as identity primary key,
  prestacion_id integer not null references public.catalogo_prestaciones(id) on delete cascade,
  campo_key text not null,
  label text not null,
  tipo text not null,
  placeholder text,
  ayuda text,
  requerido boolean not null default false,
  orden integer not null default 0,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (prestacion_id, campo_key)
);

create table if not exists public.estado_conversaciones (
  id integer generated by default as identity primary key,
  conversacion_id integer not null references public.conversaciones_whatsapp(id) on delete cascade,
  usuario_id integer references public.usuarios(id) on delete set null,
  isapre_id public.isapre_id,
  etapa public.etapa_conversacion not null default 'idle',
  prestacion_id integer references public.catalogo_prestaciones(id) on delete set null,
  campo_actual_id integer references public.catalogo_campos_prestacion(id) on delete set null,
  proceso_demo_id integer references public.procesos_demo(id) on delete set null,
  payload jsonb not null default '{}'::jsonb,
  metadata jsonb not null default '{}'::jsonb,
  last_message_id text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (conversacion_id)
);

create table if not exists public.procesos_demo (
  id integer generated by default as identity primary key,
  usuario_id integer not null references public.usuarios(id) on delete cascade,
  telefono text not null,
  isapre_id public.isapre_id not null,
  flujo text not null,
  origen text not null default 'dashboard',
  estado public.estado_proceso_demo not null default 'pendiente',
  resumen text,
  error text,
  metadata jsonb not null default '{}'::jsonb,
  intentos integer not null default 0 check (intentos >= 0),
  locked_at timestamptz,
  worker_id text,
  started_at timestamptz,
  finished_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.proceso_pasos (
  id integer generated by default as identity primary key,
  proceso_id integer not null references public.procesos_demo(id) on delete cascade,
  orden integer not null,
  etapa text not null,
  accion text not null,
  detalle text,
  url text,
  selector text,
  status text not null default 'info',
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.proceso_campos (
  id integer generated by default as identity primary key,
  proceso_id integer not null references public.procesos_demo(id) on delete cascade,
  campo_key text not null,
  label text not null,
  tipo text not null,
  selector text,
  requerido boolean not null default false,
  valor_ingresado text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (proceso_id, campo_key)
);

create index if not exists idx_reembolsos_usuario on public.reembolsos(usuario_id);
create index if not exists idx_reembolsos_estado on public.reembolsos(estado);
create index if not exists idx_reembolsos_created_at on public.reembolsos(created_at desc);
create index if not exists idx_reembolsos_worker_estado on public.reembolsos(estado, intentos, created_at);
create index if not exists idx_credenciales_usuario on public.credenciales_isapre(usuario_id);
create index if not exists idx_usuarios_telefono on public.usuarios(telefono);
create index if not exists idx_conversaciones_whatsapp_usuario on public.conversaciones_whatsapp(usuario_id);
create index if not exists idx_mensajes_whatsapp_conversacion on public.mensajes_whatsapp(conversacion_id, created_at desc);
create index if not exists idx_webhook_events_key on public.webhook_events(idempotency_key);
create index if not exists idx_catalogo_prestaciones_isapre on public.catalogo_prestaciones(isapre_id, activa, orden);
create index if not exists idx_catalogo_campos_prestacion on public.catalogo_campos_prestacion(prestacion_id, orden);
create index if not exists idx_estado_conversaciones_usuario on public.estado_conversaciones(usuario_id);
create index if not exists idx_estado_conversaciones_etapa on public.estado_conversaciones(etapa);
create index if not exists idx_procesos_demo_usuario on public.procesos_demo(usuario_id, created_at desc);
create index if not exists idx_procesos_demo_estado on public.procesos_demo(estado, intentos, created_at);
create index if not exists idx_proceso_pasos_proceso on public.proceso_pasos(proceso_id, orden);
create index if not exists idx_proceso_campos_proceso on public.proceso_campos(proceso_id);

drop trigger if exists trg_usuarios_updated_at on public.usuarios;
create trigger trg_usuarios_updated_at
before update on public.usuarios
for each row execute function public.set_updated_at();

drop trigger if exists trg_credenciales_isapre_updated_at on public.credenciales_isapre;
create trigger trg_credenciales_isapre_updated_at
before update on public.credenciales_isapre
for each row execute function public.set_updated_at();

drop trigger if exists trg_reembolsos_updated_at on public.reembolsos;
create trigger trg_reembolsos_updated_at
before update on public.reembolsos
for each row execute function public.set_updated_at();

drop trigger if exists trg_portales_status_updated_at on public.portales_status;
create trigger trg_portales_status_updated_at
before update on public.portales_status
for each row execute function public.set_updated_at();

drop trigger if exists trg_conversaciones_whatsapp_updated_at on public.conversaciones_whatsapp;
create trigger trg_conversaciones_whatsapp_updated_at
before update on public.conversaciones_whatsapp
for each row execute function public.set_updated_at();

drop trigger if exists trg_catalogo_prestaciones_updated_at on public.catalogo_prestaciones;
create trigger trg_catalogo_prestaciones_updated_at
before update on public.catalogo_prestaciones
for each row execute function public.set_updated_at();

drop trigger if exists trg_catalogo_campos_prestacion_updated_at on public.catalogo_campos_prestacion;
create trigger trg_catalogo_campos_prestacion_updated_at
before update on public.catalogo_campos_prestacion
for each row execute function public.set_updated_at();

drop trigger if exists trg_estado_conversaciones_updated_at on public.estado_conversaciones;
create trigger trg_estado_conversaciones_updated_at
before update on public.estado_conversaciones
for each row execute function public.set_updated_at();

drop trigger if exists trg_procesos_demo_updated_at on public.procesos_demo;
create trigger trg_procesos_demo_updated_at
before update on public.procesos_demo
for each row execute function public.set_updated_at();

drop trigger if exists trg_proceso_campos_updated_at on public.proceso_campos;
create trigger trg_proceso_campos_updated_at
before update on public.proceso_campos
for each row execute function public.set_updated_at();

insert into public.portales_status (isapre_id, status, ultima_ejecucion_exitosa)
values
  ('colmena', 'operativo', timezone('utc', now())),
  ('banmedica', 'operativo', timezone('utc', now())),
  ('consalud', 'operativo', timezone('utc', now())),
  ('cruzblanca', 'operativo', timezone('utc', now())),
  ('nueva_masvida', 'operativo', timezone('utc', now())),
  ('vida_tres', 'operativo', timezone('utc', now())),
  ('esencial', 'operativo', timezone('utc', now()))
on conflict (isapre_id) do nothing;

insert into public.catalogo_prestaciones (
  isapre_id,
  codigo,
  nombre,
  descripcion,
  requiere_formulario,
  requiere_adjuntos,
  activa,
  orden,
  metadata
)
values
  (
    'banmedica',
    'consultas_psicologia',
    'Consultas Médicas y Atenciones Psicológicas',
    'Prestación que hoy requiere adjuntar voucher o boleta.',
    false,
    true,
    true,
    1,
    '{"tipo_demo":"adjuntos"}'::jsonb
  ),
  (
    'banmedica',
    'examenes_y_otros',
    'Exámenes, Imagenología, Procedimientos y Otros',
    'Prestación orientada a adjuntos; el demo la deja registrada como capa preparada.',
    false,
    true,
    true,
    2,
    '{"tipo_demo":"adjuntos"}'::jsonb
  ),
  (
    'banmedica',
    'urgencias_medicas',
    'Urgencias Médicas',
    'Prestación con formulario guiado para el demo conversacional.',
    true,
    true,
    true,
    3,
    '{"tipo_demo":"formulario"}'::jsonb
  ),
  (
    'banmedica',
    'optica_kine_fono',
    'Óptica, Kinesiología y Fonoaudiología',
    'Prestación que hoy requiere adjuntos y queda preparada para fases siguientes.',
    false,
    true,
    true,
    4,
    '{"tipo_demo":"adjuntos"}'::jsonb
  )
on conflict (isapre_id, codigo) do update set
  nombre = excluded.nombre,
  descripcion = excluded.descripcion,
  requiere_formulario = excluded.requiere_formulario,
  requiere_adjuntos = excluded.requiere_adjuntos,
  activa = excluded.activa,
  orden = excluded.orden,
  metadata = excluded.metadata,
  updated_at = timezone('utc', now());

insert into public.catalogo_campos_prestacion (
  prestacion_id,
  campo_key,
  label,
  tipo,
  placeholder,
  ayuda,
  requerido,
  orden,
  metadata
)
select
  cp.id,
  data.campo_key,
  data.label,
  data.tipo,
  data.placeholder,
  data.ayuda,
  data.requerido,
  data.orden,
  data.metadata
from public.catalogo_prestaciones cp
cross join (
  values
    (
      'centro_medico_rut',
      'RUT del centro médico',
      'rut',
      'Ej: 76.123.456-7',
      'Ingresa el RUT del centro médico incluyendo dígito verificador.',
      true,
      1,
      '{"validacion":"rut"}'::jsonb
    ),
    (
      'centro_medico_nombre',
      'Nombre del centro médico',
      'text',
      'Ej: Clínica Santa María',
      'Nombre visible en el comprobante o centro de urgencia.',
      false,
      2,
      '{}'::jsonb
    ),
    (
      'fecha_atencion',
      'Fecha de atención',
      'date',
      'YYYY-MM-DD',
      'Fecha en que ocurrió la atención de urgencia.',
      true,
      3,
      '{"validacion":"date"}'::jsonb
    ),
    (
      'monto_pagado',
      'Monto pagado',
      'number',
      'Ej: 35000',
      'Monto total pagado por la atención, sin puntos.',
      false,
      4,
      '{"validacion":"number"}'::jsonb
    ),
    (
      'observaciones',
      'Observaciones',
      'text',
      'Contexto adicional',
      'Dato libre para complementar el registro del demo.',
      false,
      5,
      '{}'::jsonb
    )
) as data(campo_key, label, tipo, placeholder, ayuda, requerido, orden, metadata)
where cp.isapre_id = 'banmedica'
  and cp.codigo = 'urgencias_medicas'
on conflict (prestacion_id, campo_key) do update set
  label = excluded.label,
  tipo = excluded.tipo,
  placeholder = excluded.placeholder,
  ayuda = excluded.ayuda,
  requerido = excluded.requerido,
  orden = excluded.orden,
  metadata = excluded.metadata,
  updated_at = timezone('utc', now());

comment on table public.usuarios is 'Usuarios del sistema WSP-ISAP.';
comment on table public.credenciales_isapre is 'Credenciales de isapre cifradas a nivel de aplicación.';
comment on table public.reembolsos is 'Solicitudes de reembolso y su estado de procesamiento.';
comment on table public.portales_status is 'Estado técnico de los portales de isapres monitoreados por el worker.';
comment on table public.conversaciones_whatsapp is 'Conversaciones persistidas para interacción y trazabilidad desde WhatsApp.';
comment on table public.mensajes_whatsapp is 'Mensajes entrantes y salientes registrados para cada conversación.';
comment on table public.webhook_events is 'Registro idempotente de eventos entrantes desde Kapso.';
comment on table public.catalogo_prestaciones is 'Prestaciones disponibles por isapre para el orquestador conversacional.';
comment on table public.catalogo_campos_prestacion is 'Campos guiados por conversación para prestaciones con formulario.';
comment on table public.estado_conversaciones is 'Estado conversacional actual de cada conversación de WhatsApp.';
comment on table public.procesos_demo is 'Procesos demo de navegación RPA sin envío final del formulario.';
comment on table public.proceso_pasos is 'Bitácora de navegación del proceso demo, incluyendo botones, etapas y URLs.';
comment on table public.proceso_campos is 'Campos detectados o completados durante el demo.';
