-- WSP-ISAP - Base inicial para Supabase Postgres
-- Ejecutar este script en el SQL Editor de Supabase.
-- Mantiene compatibilidad de nombres con el esquema actual en SQLite.

create extension if not exists pgcrypto;

do $$
begin
  if not exists (select 1 from pg_type where typname = 'isapre_id') then
    create type public.isapre_id as enum (
      'colmena',
      'banmedica',
      'consalud',
      'cruzblanca',
      'nueva_masvida',
      'vida_tres',
      'esencial'
    );
  end if;

  if not exists (select 1 from pg_type where typname = 'estado_solicitud') then
    create type public.estado_solicitud as enum (
      'en_cola',
      'procesando_ocr',
      'iniciando_sesion',
      'subiendo_boleta',
      'exitoso',
      'rechazado'
    );
  end if;

  if not exists (select 1 from pg_type where typname = 'portal_status') then
    create type public.portal_status as enum (
      'operativo',
      'caido',
      'html_cambiado',
      'mantenimiento'
    );
  end if;
end $$;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create table if not exists public.usuarios (
  id integer generated by default as identity primary key,
  nombre text not null,
  telefono text not null unique,
  rut text not null,
  password_hash text not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.credenciales_isapre (
  id integer generated by default as identity primary key,
  usuario_id integer not null references public.usuarios(id) on delete cascade,
  isapre_id public.isapre_id not null,
  rut text not null,
  password_encrypted text not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (usuario_id, isapre_id)
);

create table if not exists public.reembolsos (
  id integer generated by default as identity primary key,
  usuario_id integer not null references public.usuarios(id) on delete cascade,
  rut_usuario text not null,
  isapre public.isapre_id not null,
  monto integer not null default 0 check (monto >= 0),
  fecha timestamptz not null default timezone('utc', now()),
  estado public.estado_solicitud not null default 'en_cola',
  url_documento text not null,
  folio_isapre text,
  error text,
  intentos integer not null default 0 check (intentos >= 0),
  locked_at timestamptz,
  worker_id text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.portales_status (
  isapre_id public.isapre_id primary key,
  status public.portal_status not null default 'operativo',
  ultima_ejecucion_exitosa timestamptz not null default timezone('utc', now()),
  latencia_ms integer,
  mensaje_error text,
  updated_at timestamptz not null default timezone('utc', now()),
  constraint portales_status_latencia_ms_check
    check (latencia_ms is null or latencia_ms >= 0)
);

create index if not exists idx_reembolsos_usuario on public.reembolsos(usuario_id);
create index if not exists idx_reembolsos_estado on public.reembolsos(estado);
create index if not exists idx_reembolsos_created_at on public.reembolsos(created_at desc);
create index if not exists idx_reembolsos_worker_estado on public.reembolsos(estado, intentos, created_at);
create index if not exists idx_credenciales_usuario on public.credenciales_isapre(usuario_id);
create index if not exists idx_usuarios_telefono on public.usuarios(telefono);

drop trigger if exists trg_usuarios_updated_at on public.usuarios;
create trigger trg_usuarios_updated_at
before update on public.usuarios
for each row execute function public.set_updated_at();

drop trigger if exists trg_credenciales_isapre_updated_at on public.credenciales_isapre;
create trigger trg_credenciales_isapre_updated_at
before update on public.credenciales_isapre
for each row execute function public.set_updated_at();

drop trigger if exists trg_reembolsos_updated_at on public.reembolsos;
create trigger trg_reembolsos_updated_at
before update on public.reembolsos
for each row execute function public.set_updated_at();

drop trigger if exists trg_portales_status_updated_at on public.portales_status;
create trigger trg_portales_status_updated_at
before update on public.portales_status
for each row execute function public.set_updated_at();

insert into public.portales_status (isapre_id, status, ultima_ejecucion_exitosa)
values
  ('colmena', 'operativo', timezone('utc', now())),
  ('banmedica', 'operativo', timezone('utc', now())),
  ('consalud', 'operativo', timezone('utc', now())),
  ('cruzblanca', 'operativo', timezone('utc', now())),
  ('nueva_masvida', 'operativo', timezone('utc', now())),
  ('vida_tres', 'operativo', timezone('utc', now())),
  ('esencial', 'operativo', timezone('utc', now()))
on conflict (isapre_id) do nothing;

comment on table public.usuarios is 'Usuarios del sistema WSP-ISAP.';
comment on table public.credenciales_isapre is 'Credenciales de isapre cifradas a nivel de aplicación.';
comment on table public.reembolsos is 'Solicitudes de reembolso y su estado de procesamiento.';
comment on table public.portales_status is 'Estado técnico de los portales de isapres monitoreados por el worker.';
